protected_bike_infra:
  'busway': 0
  'corridor': 0
  'cycleway': 0 
  'elevator': 1
  'footway': 1
  'living_street': 1
  'motorway': 0
  'motorway_link': 0
  'path': 1 
  'pedestrian': 0 
  'primary': 0
  'primary_link': 0
  'residential': 0
  'secondary': 0
  'secondary_link': 0 
  'service': 0
  'steps': 0
  'tertiary': 0
  'tertiary_link': 0
  'track': 1
  'trunk': 0
  'unclassified': 0