name: fbnenvdev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - osmnx>=1.9.4
  - tqdm

  # additional to the non-dev env
  - ipykernel
  - ipywidgets
  - pytest
  - pytest-cov
  - sphinx
  - numpydoc
  - myst-nb
  - pre-commit
  - jupyterlab
  - pixi-kernel
  - jupyterlab
  - matplotlib
  - pip:
      # not available via conda-forge:
      - sphinx-copybutton
      - furo
      - fixbikenet